### ISSUE TITLE
Instantiate abstract class Euclidean

### ISSUE THREAD

**Issue by pengsongyou** [YantaoShen/kpm_rw_person_reid#7]
Hi Yantao,

May I ask a question regarding the instantiation of the class Euclidean? Your code gives me such an error:
![Screenshot_2019-06-19_17-22-56](https://user-images.githubusercontent.com/14327202/59753678-38bb9a00-92b7-11e9-9259-410151ef431f.png)

I am using Python 2.7 and Pytorch 0.3. Could you please let me know how to solve this problem? Thank you in advance!

**Comment by YantaoShen** [comment]
Hi, it is because of the updating of The metirc-learn module. To be specific, it seems that this problem is caused by our code of "reid/metric_learning/euclidean.py" didn't override "get_metric" and "score_pairs" abstract methods (which are new methods) in "BaseMetricLearner" of "metric_learn.base_metric".  Maybe we can use a "super call" in "reid/metric_learning/euclidean.py" to aviod it.
